server:
  port: 10488
spring:
  datasource:                                           # 数据源的相关配置        # 数据源类型：HikariCP
    url: jdbc:mysql://14.21.59.78:3307/cdsh_DB?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=CTT
    #url: jdbc:mysql://localhost:3306/cdsh_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=CTT
    password: Bm@@#2020
    #password: qq520340
  redis:
    database: 1
    host: 47.94.40.248
    port: 6379
    password: ls123456.
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl